version: '3'
services:
    app:
        container_name: housing
        image:          housing
        build:
            context:    .
        env_file:       .env
        ports:          
            - 50051:50051
        depends_on:
            - db
        volumes:
            - .:/housing

    db:
        container_name: postgres
        image:          postgres
        restart:        always
        ports:
            - 5432:5432
        expose:
            - 5432
        volumes:
            - dbvolume:/var/lib/postgresql/data


volumes:
    dbvolume:
