# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/registration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_swagger.options import annotations_pb2 as protoc__gen__swagger_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/registration.proto',
  package='housing',
  syntax='proto3',
  serialized_options=_b('\222A\276\001\022\033\n\024Housing Registration2\0031.0*\001\0012\020application/json:\020application/jsonR;\n\003404\0224\n*Returned when the resource does not exist.\022\006\n\004\232\002\001\007R\035\n\003502\022\026\n\014Server Error\022\006\n\004\232\002\001\007R\034\n\003503\022\025\n\013Bad Gateway\022\006\n\004\232\002\001\007'),
  serialized_pb=_b('\n\x18proto/registration.proto\x12\x07housing\x1a\x1cgoogle/api/annotations.proto\x1a,protoc-gen-swagger/options/annotations.proto\"\x06\n\x04Void\"1\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04\x64orm\x18\x03 \x01(\t\"=\n\x0eStudentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nchangeDorm\x18\x02 \x01(\x08\x12\x0b\n\x03new\x18\x03 \x01(\t\"@\n\x0fStudentResponse\x12!\n\x07student\x18\x01 \x01(\x0b\x32\x10.housing.Student\x12\n\n\x02ok\x18\x02 \x01(\x08\x32\xea\x04\n\x0cRegistration\x12\xa0\x01\n\rCreateStudent\x12\x10.housing.Student\x1a\x18.housing.StudentResponse\"c\x82\xd3\xe4\x93\x02\x17\"\x12/students/register:\x01*\x92\x41\x43\x12\rSummary: test\x1a\x10\x44\x65scription TestJ \n\x03\x32\x30\x30\x12\x19\n\x0fOverwrites YEET\x12\x06\n\x04\x9a\x02\x01\x07\x12X\n\x0bReadStudent\x12\x17.housing.StudentRequest\x1a\x18.housing.StudentResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/students/{id}\x12\x64\n\rUpdateStudent\x12\x17.housing.StudentRequest\x1a\x18.housing.StudentResponse\" \x82\xd3\xe4\x93\x02\x1a\x1a\x15/students/update/{id}:\x01*\x12\x61\n\rDeleteStudent\x12\x17.housing.StudentRequest\x1a\x18.housing.StudentResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/students/delete/{id}\x12L\n\x0cListStudents\x12\r.housing.Void\x1a\x18.housing.StudentResponse\"\x11\x82\xd3\xe4\x93\x02\x0b\x12\t/students0\x01\x12\x46\n\rClearStudents\x12\r.housing.Void\x1a\r.housing.Void\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/students/clearB\xc2\x01\x92\x41\xbe\x01\x12\x1b\n\x14Housing Registration2\x03\x31.0*\x01\x01\x32\x10\x61pplication/json:\x10\x61pplication/jsonR;\n\x03\x34\x30\x34\x12\x34\n*Returned when the resource does not exist.\x12\x06\n\x04\x9a\x02\x01\x07R\x1d\n\x03\x35\x30\x32\x12\x16\n\x0cServer Error\x12\x06\n\x04\x9a\x02\x01\x07R\x1c\n\x03\x35\x30\x33\x12\x15\n\x0b\x42\x61\x64 Gateway\x12\x06\n\x04\x9a\x02\x01\x07\x62\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,protoc__gen__swagger_dot_options_dot_annotations__pb2.DESCRIPTOR,])




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='housing.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=119,
)


_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='housing.Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='housing.Student.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='housing.Student.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dorm', full_name='housing.Student.dorm', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=170,
)


_STUDENTREQUEST = _descriptor.Descriptor(
  name='StudentRequest',
  full_name='housing.StudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='housing.StudentRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changeDorm', full_name='housing.StudentRequest.changeDorm', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new', full_name='housing.StudentRequest.new', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=233,
)


_STUDENTRESPONSE = _descriptor.Descriptor(
  name='StudentResponse',
  full_name='housing.StudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student', full_name='housing.StudentResponse.student', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ok', full_name='housing.StudentResponse.ok', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=299,
)

_STUDENTRESPONSE.fields_by_name['student'].message_type = _STUDENT
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
DESCRIPTOR.message_types_by_name['StudentRequest'] = _STUDENTREQUEST
DESCRIPTOR.message_types_by_name['StudentResponse'] = _STUDENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'proto.registration_pb2'
  # @@protoc_insertion_point(class_scope:housing.Void)
  ))
_sym_db.RegisterMessage(Void)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), dict(
  DESCRIPTOR = _STUDENT,
  __module__ = 'proto.registration_pb2'
  # @@protoc_insertion_point(class_scope:housing.Student)
  ))
_sym_db.RegisterMessage(Student)

StudentRequest = _reflection.GeneratedProtocolMessageType('StudentRequest', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTREQUEST,
  __module__ = 'proto.registration_pb2'
  # @@protoc_insertion_point(class_scope:housing.StudentRequest)
  ))
_sym_db.RegisterMessage(StudentRequest)

StudentResponse = _reflection.GeneratedProtocolMessageType('StudentResponse', (_message.Message,), dict(
  DESCRIPTOR = _STUDENTRESPONSE,
  __module__ = 'proto.registration_pb2'
  # @@protoc_insertion_point(class_scope:housing.StudentResponse)
  ))
_sym_db.RegisterMessage(StudentResponse)


DESCRIPTOR._options = None

_REGISTRATION = _descriptor.ServiceDescriptor(
  name='Registration',
  full_name='housing.Registration',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=302,
  serialized_end=920,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateStudent',
    full_name='housing.Registration.CreateStudent',
    index=0,
    containing_service=None,
    input_type=_STUDENT,
    output_type=_STUDENTRESPONSE,
    serialized_options=_b('\202\323\344\223\002\027\"\022/students/register:\001*\222AC\022\rSummary: test\032\020Description TestJ \n\003200\022\031\n\017Overwrites YEET\022\006\n\004\232\002\001\007'),
  ),
  _descriptor.MethodDescriptor(
    name='ReadStudent',
    full_name='housing.Registration.ReadStudent',
    index=1,
    containing_service=None,
    input_type=_STUDENTREQUEST,
    output_type=_STUDENTRESPONSE,
    serialized_options=_b('\202\323\344\223\002\020\022\016/students/{id}'),
  ),
  _descriptor.MethodDescriptor(
    name='UpdateStudent',
    full_name='housing.Registration.UpdateStudent',
    index=2,
    containing_service=None,
    input_type=_STUDENTREQUEST,
    output_type=_STUDENTRESPONSE,
    serialized_options=_b('\202\323\344\223\002\032\032\025/students/update/{id}:\001*'),
  ),
  _descriptor.MethodDescriptor(
    name='DeleteStudent',
    full_name='housing.Registration.DeleteStudent',
    index=3,
    containing_service=None,
    input_type=_STUDENTREQUEST,
    output_type=_STUDENTRESPONSE,
    serialized_options=_b('\202\323\344\223\002\027*\025/students/delete/{id}'),
  ),
  _descriptor.MethodDescriptor(
    name='ListStudents',
    full_name='housing.Registration.ListStudents',
    index=4,
    containing_service=None,
    input_type=_VOID,
    output_type=_STUDENTRESPONSE,
    serialized_options=_b('\202\323\344\223\002\013\022\t/students'),
  ),
  _descriptor.MethodDescriptor(
    name='ClearStudents',
    full_name='housing.Registration.ClearStudents',
    index=5,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=_b('\202\323\344\223\002\021*\017/students/clear'),
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTRATION)

DESCRIPTOR.services_by_name['Registration'] = _REGISTRATION

# @@protoc_insertion_point(module_scope)
