# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import registration_pb2 as proto_dot_registration__pb2


class RegistrationStub(object):
  """*
  Defines the services a client can use to register for housing.

  RPC Methods:

  CreateStudent   -   adds a new student registration

  ReadStudent     -   returns a single student from database given an
  id number

  UpdateStudent   -   updates either the name or dorm of a student given
  an id number request

  DeleteStudent   -   deletes a student given an id number request

  ListStudent     -   lists all the students in the database

  ClearStudents   -   clears student registrations (not for client use)
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateStudent = channel.unary_unary(
        '/housing.Registration/CreateStudent',
        request_serializer=proto_dot_registration__pb2.Student.SerializeToString,
        response_deserializer=proto_dot_registration__pb2.StudentResponse.FromString,
        )
    self.ReadStudent = channel.unary_unary(
        '/housing.Registration/ReadStudent',
        request_serializer=proto_dot_registration__pb2.StudentRequest.SerializeToString,
        response_deserializer=proto_dot_registration__pb2.StudentResponse.FromString,
        )
    self.UpdateStudent = channel.unary_unary(
        '/housing.Registration/UpdateStudent',
        request_serializer=proto_dot_registration__pb2.StudentRequest.SerializeToString,
        response_deserializer=proto_dot_registration__pb2.StudentResponse.FromString,
        )
    self.DeleteStudent = channel.unary_unary(
        '/housing.Registration/DeleteStudent',
        request_serializer=proto_dot_registration__pb2.StudentRequest.SerializeToString,
        response_deserializer=proto_dot_registration__pb2.StudentResponse.FromString,
        )
    self.ListStudents = channel.unary_stream(
        '/housing.Registration/ListStudents',
        request_serializer=proto_dot_registration__pb2.Void.SerializeToString,
        response_deserializer=proto_dot_registration__pb2.StudentResponse.FromString,
        )
    self.ClearStudents = channel.unary_unary(
        '/housing.Registration/ClearStudents',
        request_serializer=proto_dot_registration__pb2.Void.SerializeToString,
        response_deserializer=proto_dot_registration__pb2.Void.FromString,
        )


class RegistrationServicer(object):
  """*
  Defines the services a client can use to register for housing.

  RPC Methods:

  CreateStudent   -   adds a new student registration

  ReadStudent     -   returns a single student from database given an
  id number

  UpdateStudent   -   updates either the name or dorm of a student given
  an id number request

  DeleteStudent   -   deletes a student given an id number request

  ListStudent     -   lists all the students in the database

  ClearStudents   -   clears student registrations (not for client use)
  """

  def CreateStudent(self, request, context):
    """/ Creates a student from a student message. Returns created student with
    ok response
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ReadStudent(self, request, context):
    """/ Reads a student, queried by id number. Returns student with ok response
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateStudent(self, request, context):
    """/ Updates a student's name or dorm. Specified by `changeDorm` boolean.
    Returns new student.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteStudent(self, request, context):
    """/ Deletes a registration queried by id and returns the deleted student
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListStudents(self, request, context):
    """/ Lists all the registered students. Returns a stream of students
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ClearStudents(self, request, context):
    """/ Removes all registered students
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RegistrationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateStudent': grpc.unary_unary_rpc_method_handler(
          servicer.CreateStudent,
          request_deserializer=proto_dot_registration__pb2.Student.FromString,
          response_serializer=proto_dot_registration__pb2.StudentResponse.SerializeToString,
      ),
      'ReadStudent': grpc.unary_unary_rpc_method_handler(
          servicer.ReadStudent,
          request_deserializer=proto_dot_registration__pb2.StudentRequest.FromString,
          response_serializer=proto_dot_registration__pb2.StudentResponse.SerializeToString,
      ),
      'UpdateStudent': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateStudent,
          request_deserializer=proto_dot_registration__pb2.StudentRequest.FromString,
          response_serializer=proto_dot_registration__pb2.StudentResponse.SerializeToString,
      ),
      'DeleteStudent': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteStudent,
          request_deserializer=proto_dot_registration__pb2.StudentRequest.FromString,
          response_serializer=proto_dot_registration__pb2.StudentResponse.SerializeToString,
      ),
      'ListStudents': grpc.unary_stream_rpc_method_handler(
          servicer.ListStudents,
          request_deserializer=proto_dot_registration__pb2.Void.FromString,
          response_serializer=proto_dot_registration__pb2.StudentResponse.SerializeToString,
      ),
      'ClearStudents': grpc.unary_unary_rpc_method_handler(
          servicer.ClearStudents,
          request_deserializer=proto_dot_registration__pb2.Void.FromString,
          response_serializer=proto_dot_registration__pb2.Void.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'housing.Registration', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
