version: '3'
services:
    app:
        container_name: server_recruiter
        image:          server_recruiter
        build:
            context:    .
            dockerfile: Dockerfile-python
        env_file:       .env
        ports:          
            - 50051:50051
        depends_on:
            - db
        volumes:
            - ./app:/service/app

    envoy:
        container_name: envoy_recruiter
        image: envoyproxy/envoy-dev:latest
        build:
            context:    .
            dockerfile: Dockerfile-envoy
        ports:
            - 4748:4748
        volumes:
            - ./envoy/envoy-front.yaml:/etc/envoy-front.yaml
            - ./proto:/proto

    db:
        container_name: postgres_recruiter
        image:          postgres
        restart:        always
        ports:
            - 5432:5432
        expose:
            - 5432
        volumes:
            - dbvolume:/var/lib/postgresql/data

    nginx:
      container_name: nginx_recruiter
      image:          nginx
      ports:
          - 8080:8080
      expose:
          - 8080
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
    dbvolume:
