// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/registration.proto

package housing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// Empty message for rpc's that require no request (clear and list)
type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_70818ed37065cccf, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

//*
// Represents a student with a unique id, a name, and a dorm
type Student struct {
	//* unique id for each student
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//* first and last name of a student
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//* dorm choice
	Dorm                 string   `protobuf:"bytes,3,opt,name=dorm,proto3" json:"dorm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_70818ed37065cccf, []int{1}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetDorm() string {
	if m != nil {
		return m.Dorm
	}
	return ""
}

//*
// A request made by a client, specifiying id of a student. `changeDorm` and
// `new` are set when updating a student.
type StudentRequest struct {
	//* Unique id student query
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//* True if the client requests to change the dorm, false to change name
	ChangeDorm bool `protobuf:"varint,2,opt,name=changeDorm,proto3" json:"changeDorm,omitempty"`
	//* The updated value
	New                  string   `protobuf:"bytes,3,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentRequest) Reset()         { *m = StudentRequest{} }
func (m *StudentRequest) String() string { return proto.CompactTextString(m) }
func (*StudentRequest) ProtoMessage()    {}
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70818ed37065cccf, []int{2}
}

func (m *StudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentRequest.Unmarshal(m, b)
}
func (m *StudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentRequest.Marshal(b, m, deterministic)
}
func (m *StudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentRequest.Merge(m, src)
}
func (m *StudentRequest) XXX_Size() int {
	return xxx_messageInfo_StudentRequest.Size(m)
}
func (m *StudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentRequest proto.InternalMessageInfo

func (m *StudentRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StudentRequest) GetChangeDorm() bool {
	if m != nil {
		return m.ChangeDorm
	}
	return false
}

func (m *StudentRequest) GetNew() string {
	if m != nil {
		return m.New
	}
	return ""
}

//*
// A response sent by a server, returning a student message and a boolean field
// indicating a successful transaction
type StudentResponse struct {
	//*
	// The deleted, created, or retrieved student. If response is not `ok`,
	// id = 0, name = dorm = "ERROR"
	Student *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	//* True if transaction is successful, false otherwise
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentResponse) Reset()         { *m = StudentResponse{} }
func (m *StudentResponse) String() string { return proto.CompactTextString(m) }
func (*StudentResponse) ProtoMessage()    {}
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70818ed37065cccf, []int{3}
}

func (m *StudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentResponse.Unmarshal(m, b)
}
func (m *StudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentResponse.Marshal(b, m, deterministic)
}
func (m *StudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentResponse.Merge(m, src)
}
func (m *StudentResponse) XXX_Size() int {
	return xxx_messageInfo_StudentResponse.Size(m)
}
func (m *StudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StudentResponse proto.InternalMessageInfo

func (m *StudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

func (m *StudentResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Void)(nil), "housing.Void")
	proto.RegisterType((*Student)(nil), "housing.Student")
	proto.RegisterType((*StudentRequest)(nil), "housing.StudentRequest")
	proto.RegisterType((*StudentResponse)(nil), "housing.StudentResponse")
}

func init() { proto.RegisterFile("proto/registration.proto", fileDescriptor_70818ed37065cccf) }

var fileDescriptor_70818ed37065cccf = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x3f, 0xae, 0xd3, 0x40,
	0x10, 0xc6, 0x65, 0xbf, 0xf0, 0xc2, 0x9b, 0xc4, 0xf9, 0xb3, 0x12, 0xc4, 0xb2, 0x00, 0x45, 0xae,
	0x22, 0x17, 0x31, 0x0a, 0x1d, 0x1d, 0x4a, 0x44, 0x15, 0x1a, 0x23, 0x10, 0xa2, 0x5b, 0xb2, 0x23,
	0x67, 0x95, 0x64, 0xd7, 0x78, 0xd7, 0xa2, 0x40, 0x34, 0x5c, 0x81, 0x23, 0x70, 0x24, 0xae, 0xc0,
	0x41, 0xd0, 0xae, 0xd7, 0x89, 0x91, 0x45, 0x0a, 0x5e, 0x37, 0xfe, 0x34, 0xf3, 0xfb, 0xbe, 0x19,
	0xdb, 0x10, 0x16, 0xa5, 0xd4, 0x32, 0x2d, 0x31, 0xe7, 0x4a, 0x97, 0x54, 0x73, 0x29, 0x96, 0x56,
	0x22, 0xfd, 0xbd, 0xac, 0x14, 0x17, 0x79, 0xf4, 0x24, 0x97, 0x32, 0x3f, 0x62, 0x4a, 0x0b, 0x9e,
	0x52, 0x21, 0xa4, 0xb6, 0x5d, 0xaa, 0x6e, 0x8b, 0x6f, 0xa1, 0xf7, 0x5e, 0x72, 0x16, 0xbf, 0x82,
	0xfe, 0x5b, 0x5d, 0x31, 0x14, 0x9a, 0x8c, 0xc0, 0xe7, 0x2c, 0xf4, 0xe6, 0xde, 0xe2, 0x41, 0xe6,
	0x73, 0x46, 0x08, 0xf4, 0x04, 0x3d, 0x61, 0xe8, 0xcf, 0xbd, 0xc5, 0x5d, 0x66, 0x6b, 0xa3, 0x31,
	0x59, 0x9e, 0xc2, 0x9b, 0x5a, 0x33, 0x75, 0x9c, 0xc1, 0xc8, 0x21, 0x32, 0xfc, 0x5c, 0xa1, 0xea,
	0x92, 0x9e, 0x01, 0xec, 0xf6, 0x54, 0xe4, 0xb8, 0x31, 0xb3, 0x86, 0xf7, 0x30, 0x6b, 0x29, 0x64,
	0x02, 0x37, 0x02, 0xbf, 0x38, 0xa8, 0x29, 0xe3, 0x37, 0x30, 0x3e, 0x33, 0x55, 0x21, 0x85, 0x42,
	0x92, 0x40, 0x5f, 0xd5, 0x92, 0x25, 0x0f, 0x56, 0x93, 0xa5, 0x5b, 0x75, 0xd9, 0xb4, 0x36, 0x0d,
	0x26, 0x80, 0x3c, 0x38, 0x23, 0x5f, 0x1e, 0x56, 0x3f, 0x7b, 0x30, 0xcc, 0x5a, 0xb7, 0x22, 0x1f,
	0x21, 0x58, 0x97, 0x48, 0x35, 0x36, 0xcb, 0x77, 0x60, 0x51, 0xd8, 0xc1, 0xbb, 0x24, 0xf1, 0xd3,
	0xef, 0xbf, 0x7e, 0xff, 0xf0, 0x67, 0x31, 0x49, 0x9d, 0x9f, 0x72, 0x2f, 0x02, 0xcb, 0x97, 0x5e,
	0x42, 0x3e, 0xc0, 0x20, 0x43, 0xca, 0x1a, 0xf2, 0xac, 0xcb, 0xb1, 0x57, 0xba, 0x62, 0xf0, 0xd8,
	0x1a, 0x4c, 0xc8, 0xe8, 0x62, 0xf0, 0x95, 0xb3, 0x6f, 0x84, 0x41, 0xf0, 0xae, 0x60, 0xad, 0xd4,
	0xff, 0xc1, 0x9e, 0x5b, 0x76, 0x14, 0x3d, 0xba, 0xb0, 0x2b, 0xcb, 0xb4, 0x16, 0x26, 0x3f, 0x85,
	0x60, 0x83, 0x47, 0xbc, 0x97, 0x8b, 0x3b, 0x51, 0xd2, 0x72, 0x61, 0x96, 0x59, 0x2f, 0xb2, 0x85,
	0xe1, 0x96, 0x2b, 0xed, 0xa6, 0x14, 0x09, 0xce, 0x20, 0xf3, 0x51, 0x5e, 0xe1, 0x4e, 0x2d, 0x77,
	0x40, 0xee, 0xce, 0xdc, 0xe7, 0x1e, 0x79, 0x0d, 0xc1, 0xfa, 0x88, 0xb4, 0xfc, 0x17, 0xee, 0xef,
	0xc7, 0x78, 0x66, 0x19, 0xd3, 0x64, 0x7c, 0xc9, 0xb6, 0x33, 0xe3, 0x9f, 0x6e, 0xed, 0xaf, 0xf1,
	0xe2, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x0c, 0x3c, 0x12, 0x5d, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistrationClient is the client API for Registration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistrationClient interface {
	/// Creates a student from a student message. Returns created student with
	// ok response
	CreateStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*StudentResponse, error)
	/// Reads a student, queried by id number. Returns student with ok response
	ReadStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error)
	/// Updates a student's name or dorm. Specified by `changeDorm` boolean.
	// Returns new student.
	UpdateStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error)
	/// Deletes a registration queried by id and returns the deleted student
	DeleteStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error)
	/// Lists all the registered students. Returns a stream of students
	ListStudents(ctx context.Context, in *Void, opts ...grpc.CallOption) (Registration_ListStudentsClient, error)
	/// Removes all registered students
	ClearStudents(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
}

type registrationClient struct {
	cc *grpc.ClientConn
}

func NewRegistrationClient(cc *grpc.ClientConn) RegistrationClient {
	return &registrationClient{cc}
}

func (c *registrationClient) CreateStudent(ctx context.Context, in *Student, opts ...grpc.CallOption) (*StudentResponse, error) {
	out := new(StudentResponse)
	err := c.cc.Invoke(ctx, "/housing.Registration/CreateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) ReadStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error) {
	out := new(StudentResponse)
	err := c.cc.Invoke(ctx, "/housing.Registration/ReadStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) UpdateStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error) {
	out := new(StudentResponse)
	err := c.cc.Invoke(ctx, "/housing.Registration/UpdateStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) DeleteStudent(ctx context.Context, in *StudentRequest, opts ...grpc.CallOption) (*StudentResponse, error) {
	out := new(StudentResponse)
	err := c.cc.Invoke(ctx, "/housing.Registration/DeleteStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) ListStudents(ctx context.Context, in *Void, opts ...grpc.CallOption) (Registration_ListStudentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Registration_serviceDesc.Streams[0], "/housing.Registration/ListStudents", opts...)
	if err != nil {
		return nil, err
	}
	x := &registrationListStudentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registration_ListStudentsClient interface {
	Recv() (*StudentResponse, error)
	grpc.ClientStream
}

type registrationListStudentsClient struct {
	grpc.ClientStream
}

func (x *registrationListStudentsClient) Recv() (*StudentResponse, error) {
	m := new(StudentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registrationClient) ClearStudents(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/housing.Registration/ClearStudents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServer is the server API for Registration service.
type RegistrationServer interface {
	/// Creates a student from a student message. Returns created student with
	// ok response
	CreateStudent(context.Context, *Student) (*StudentResponse, error)
	/// Reads a student, queried by id number. Returns student with ok response
	ReadStudent(context.Context, *StudentRequest) (*StudentResponse, error)
	/// Updates a student's name or dorm. Specified by `changeDorm` boolean.
	// Returns new student.
	UpdateStudent(context.Context, *StudentRequest) (*StudentResponse, error)
	/// Deletes a registration queried by id and returns the deleted student
	DeleteStudent(context.Context, *StudentRequest) (*StudentResponse, error)
	/// Lists all the registered students. Returns a stream of students
	ListStudents(*Void, Registration_ListStudentsServer) error
	/// Removes all registered students
	ClearStudents(context.Context, *Void) (*Void, error)
}

// UnimplementedRegistrationServer can be embedded to have forward compatible implementations.
type UnimplementedRegistrationServer struct {
}

func (*UnimplementedRegistrationServer) CreateStudent(ctx context.Context, req *Student) (*StudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudent not implemented")
}
func (*UnimplementedRegistrationServer) ReadStudent(ctx context.Context, req *StudentRequest) (*StudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadStudent not implemented")
}
func (*UnimplementedRegistrationServer) UpdateStudent(ctx context.Context, req *StudentRequest) (*StudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudent not implemented")
}
func (*UnimplementedRegistrationServer) DeleteStudent(ctx context.Context, req *StudentRequest) (*StudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStudent not implemented")
}
func (*UnimplementedRegistrationServer) ListStudents(req *Void, srv Registration_ListStudentsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListStudents not implemented")
}
func (*UnimplementedRegistrationServer) ClearStudents(ctx context.Context, req *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearStudents not implemented")
}

func RegisterRegistrationServer(s *grpc.Server, srv RegistrationServer) {
	s.RegisterService(&_Registration_serviceDesc, srv)
}

func _Registration_CreateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).CreateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housing.Registration/CreateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).CreateStudent(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_ReadStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).ReadStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housing.Registration/ReadStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).ReadStudent(ctx, req.(*StudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_UpdateStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).UpdateStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housing.Registration/UpdateStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).UpdateStudent(ctx, req.(*StudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_DeleteStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).DeleteStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housing.Registration/DeleteStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).DeleteStudent(ctx, req.(*StudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_ListStudents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistrationServer).ListStudents(m, &registrationListStudentsServer{stream})
}

type Registration_ListStudentsServer interface {
	Send(*StudentResponse) error
	grpc.ServerStream
}

type registrationListStudentsServer struct {
	grpc.ServerStream
}

func (x *registrationListStudentsServer) Send(m *StudentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Registration_ClearStudents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).ClearStudents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/housing.Registration/ClearStudents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).ClearStudents(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "housing.Registration",
	HandlerType: (*RegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStudent",
			Handler:    _Registration_CreateStudent_Handler,
		},
		{
			MethodName: "ReadStudent",
			Handler:    _Registration_ReadStudent_Handler,
		},
		{
			MethodName: "UpdateStudent",
			Handler:    _Registration_UpdateStudent_Handler,
		},
		{
			MethodName: "DeleteStudent",
			Handler:    _Registration_DeleteStudent_Handler,
		},
		{
			MethodName: "ClearStudents",
			Handler:    _Registration_ClearStudents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListStudents",
			Handler:       _Registration_ListStudents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/registration.proto",
}
